stages:
  - test_and_upload
  - name: publish
    if: NOT (type = pull_request)
branches:
  only:
    - develop
jobs:
  include:
    - os: windows
      stage: test_and_upload
      env: KBUILD=windows
      language: shell # java is not supported but jdk is installed
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" && $TRAVIS_BRANCH == "develop" ]; then  powershell -Command "cmd /c travis_win.bat"; fi'
    - os: osx
      stage: test_and_upload
      env:
        KBUILD=macos
        JAVA_OPTS=-Xmx2g
      language: java
      jdk: openjdk10
      before_install:
        - cp $(/usr/libexec/java_home)/lib/security/cacerts "${JAVA_HOME}/lib/security/cacerts"
      install:
        - echo install
      before_script:
        - echo before_script
        - chmod +x ./gradlew
        - echo $TRAVIS_BRANCH
        - echo $TRAVIS_PULL_REQUEST
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" && $TRAVIS_BRANCH == "develop" ]; then ./gradlew -s -i publishMacosX64ZipPublicationToMavenRepository; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" && $TRAVIS_BRANCH == "develop" ]; then ./gradlew -s -i publishLinuxX64ZipPublicationToMavenRepository; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" && $TRAVIS_BRANCH == "develop" ]; then echo asdasdasd; fi'