version: '3'

services:
  drill-admin:
    build:
      context: ..
      dockerfile: drill-admin/Dockerfile
    ports:
      - 8090:8090
      - 5006:5006
    networks:
      - drill4j-dev-network
    environment:
      - isDocker=true
      - DRILL_HOME=/drill
      - POSTGRES_HOST=postgresdb
      - POSTGRES_PORT=5432
    restart: always
    depends_on:
      - postgresdb

  postgresdb:
    image:
      postgres:11.3
    restart:
      always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=drill_base
    networks:
      - drill4j-dev-network

networks:
  drill4j-dev-network:
    external:
      name: drill4j-dev-network
