name: Check agent
on:
  pull_request:
    branches:
      - develop

jobs:
  check_nix:
    name: Check for nix platforms (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 5.6.4
          arguments: --no-daemon check