name: Build & publish drill artifacts
on:
  push:
    branches:
      - develop
    tags:
      - 'v[0-9]*.[0-9]*.0'

jobs:
  build_and_publish_for_nix:
    name: Publish for nix platforms (macOS, Linux)
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check
        run: gradle -si --no-daemon check
      - name: Publish
        run: |
          gradle check
          gradle publish
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
  build_and_publish_for_win:
    name: Publish for Windows platform (Windows platform)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build & Test
        run: |
          gradle -si --no-daemon build mingwX64Test
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false
      - name: Publish
        run: |
          gradle --no-daemon -s -i publishMingwX64ZipPublicationToMavenRepository
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
      - name: Increment
        run: |
          gradle --no-daemon incrementVersion \
          -PgithubUserName=${githubUserName} \
          -PgithubUserPassword=${githubUserPassword}
        env:
          githubUserName: ${{ secrets.githubUserName }}
          githubUserPassword: ${{ secrets.githubUserPassword }